/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucsc.ce.view;

import edu.ucsc.ce.controllers.CourseController;
import edu.ucsc.ce.controllers.LecturerController;
import edu.ucsc.ce.models.CourseDTO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jinadi
 */
public class CourseSettingForm extends javax.swing.JPanel {

    /**
     * Creates new form CourseSettingForm
     */
    public CourseSettingForm() {
        initComponents();
        loadCourseID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtss1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtss2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtcreaditPerSem = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel13.setText("ID");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 160, 70));

        txtID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 300, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setText("Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 70));

        txtName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setText("Subject per sem 1");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 70));

        txtss1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 100, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setText("Subject per sem 2");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 160, 70));

        txtss2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtss2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 110, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel12.setText("Year");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 80));

        txtyear.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });
        add(txtyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 310, 40));

        txttype.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });
        add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 310, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setText("Type");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 80));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel15.setText("Creadit per sem");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, 80));

        txtcreaditPerSem.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtcreaditPerSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcreaditPerSemActionPerformed(evt);
            }
        });
        add(txtcreaditPerSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 310, 40));

        jLabel20.setBackground(new java.awt.Color(153, 153, 153));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("            Add");
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 150, 30));

        jLabel21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("           Cancel");
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void txtcreaditPerSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcreaditPerSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcreaditPerSemActionPerformed

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        jLabel20.setBackground(Color.BLACK);
        jLabel20.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        jLabel20.setBackground(Color.GRAY);
        jLabel20.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        jLabel20.setBackground(Color.BLACK);
        jLabel20.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jLabel20.setBackground(Color.GRAY);
        jLabel20.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
    add();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtcreaditPerSem;
    private javax.swing.JTextField txtss1;
    private javax.swing.JTextField txtss2;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables

    private void add() {
        try {
            CourseDTO cdto=new CourseDTO(txtID.getText(), txtName.getText(),Integer.parseInt(txtss1.getText()), Integer.parseInt(txtss2.getText()), Integer.parseInt(txtyear.getText()),txttype.getText(),Integer.parseInt(txtcreaditPerSem.getText()));
            boolean add=CourseController.addCourse(cdto);
            if (add) {
                JOptionPane.showMessageDialog(null, "Course Added sucessfully");
            } else {
                JOptionPane.showMessageDialog(null, "OOPz!Try Again");
            }
        } catch (SQLException | ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(null, "OOPz!Try Again");
            Logger.getLogger(CourseSettingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCourseID() {
        try {
            String lecID = CourseController.getLastCourseID();
            if (lecID.equals("")) {
                txtID.setText("LEC001");
            } else {
                String id = lecID.substring(lecID.length() - 1, lecID.length());
                txtID.setText(lecID.substring(0, lecID.length()-1) + (Integer.parseInt(id) + 1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(CourseSettingForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CourseSettingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
 }
}
