/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucsc.ce.view;

import java.awt.Color;

/**
 *
 * @author Jinadi
 */
public class LabUpdateForm extends javax.swing.JPanel {

    /**
     * Creates new form LabUpdateForm
     */
    public LabUpdateForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCom = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel13.setText("ID");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 160, 70));

        txtID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 300, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setText("Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 70));

        txtName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 310, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setText("size");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 70));

        txtSize.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 100, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setText("num of computers");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 160, 70));

        txtCom.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        add(txtCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 110, 40));

        txtType.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 310, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel12.setText("type");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 80));

        jLabel21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("           Cancel");
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 150, 30));

        jLabel20.setBackground(new java.awt.Color(153, 153, 153));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("            Update");
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        jLabel21.setBackground(Color.BLACK);
        jLabel20.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        jLabel21.setBackground(Color.GRAY);
        jLabel20.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        jLabel20.setBackground(Color.BLACK);
        jLabel20.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        jLabel20.setBackground(Color.GRAY);
        jLabel20.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel20MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
