/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucsc.ce.view;

/**
 *
 * @author Jinadi
 */
public class PostGraduate extends javax.swing.JPanel {

    /**
     * Creates new form PostGraduate
     */
    public PostGraduate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPost = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbYear = new javax.swing.JComboBox<>();
        txtInstitute = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuali = new javax.swing.JTextArea();

        setOpaque(false);

        pnlPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPost.setOpaque(false);
        pnlPost.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel13.setText("Year");
        pnlPost.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setText("Qualification");
        pnlPost.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setText("Institute");
        pnlPost.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 170, 50));

        cmbYear.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        pnlPost.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 130, 40));

        txtInstitute.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        pnlPost.add(txtInstitute, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 250, 30));

        txtQuali.setColumns(20);
        txtQuali.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtQuali.setRows(5);
        jScrollPane2.setViewportView(txtQuali);

        pnlPost.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 330, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pnlPost, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPost, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlPost;
    private javax.swing.JTextField txtInstitute;
    private javax.swing.JTextArea txtQuali;
    // End of variables declaration//GEN-END:variables
}
